//! CraftNext tool — autonomous self-direction via prompt generation.
//!
//! The agent calls this tool to generate its own next prompt. A side-query
//! reads entity memory, project state, and recent context to produce a
//! well-structured action prompt that gets injected as the next user message.
//!
//! This enables autonomous agent operation: the agent finishes a task,
//! calls craft_next, receives a strategic next-step prompt, and continues
//! working without human intervention.
//!
//! The side-query runs on a cheap/fast model to minimize cost.
//! The generated prompt is returned as the tool result, and the agent loop
//! treats it as the next instruction to follow.

use anyhow::Result;
use async_trait::async_trait;
use sigil_core::traits::{
    ChatRequest, Message, MessageContent, Provider, Role, Tool, ToolResult, ToolSpec,
};
use std::sync::Arc;
use tracing::debug;

/// Tool that generates the agent's next action prompt via a side-query.
pub struct CraftNextTool {
    /// Provider for the side-query (can be a cheap/fast model).
    provider: Arc<dyn Provider>,
    /// Model to use for the side-query.
    model: String,
    /// Agent name for context.
    agent_name: String,
}

impl CraftNextTool {
    pub fn new(provider: Arc<dyn Provider>, model: String, agent_name: String) -> Self {
        Self {
            provider,
            model,
            agent_name,
        }
    }
}

#[async_trait]
impl Tool for CraftNextTool {
    async fn execute(&self, args: serde_json::Value) -> Result<ToolResult> {
        let context = args.get("context").and_then(|v| v.as_str()).unwrap_or("");
        let goal = args
            .get("goal")
            .and_then(|v| v.as_str())
            .unwrap_or("Continue working toward the user's objectives.");
        let completed = args
            .get("completed")
            .and_then(|v| v.as_str())
            .unwrap_or("(not specified)");
        let constraints = args
            .get("constraints")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        let craft_prompt = format!(
            "You are a prompt engineer generating the next action prompt for an AI agent named '{}'.\n\n\
             The agent just completed some work and needs to decide what to do next.\n\n\
             ## What was just completed\n{completed}\n\n\
             ## Overall goal\n{goal}\n\n\
             ## Current context\n{context}\n\n\
             {}\
             ## Your task\n\n\
             Generate a clear, specific, actionable prompt that the agent should follow next.\n\
             The prompt should:\n\
             1. Be specific — reference exact files, functions, or tasks\n\
             2. Be actionable — the agent can start immediately without asking questions\n\
             3. Build on what was completed — don't repeat finished work\n\
             4. Move toward the overall goal\n\
             5. Be concise — 2-5 sentences, not a wall of text\n\n\
             Output ONLY the prompt text. No preamble, no explanation, no markdown formatting.\n\
             Write it as if the user is speaking directly to the agent.",
            self.agent_name,
            if constraints.is_empty() {
                String::new()
            } else {
                format!("## Constraints\n{constraints}\n\n")
            },
        );

        let request = ChatRequest {
            model: self.model.clone(),
            messages: vec![Message {
                role: Role::User,
                content: MessageContent::text(&craft_prompt),
            }],
            tools: vec![],
            max_tokens: 512,
            temperature: 0.3,
        };

        debug!(
            agent = %self.agent_name,
            model = %self.model,
            "craft_next: generating next prompt via side-query"
        );

        match self.provider.chat(&request).await {
            Ok(response) => {
                let prompt = response
                    .content
                    .unwrap_or_else(|| "Continue with the current task.".to_string());

                debug!(
                    agent = %self.agent_name,
                    prompt_len = prompt.len(),
                    "craft_next: generated prompt"
                );

                Ok(ToolResult::success(format!(
                    "NEXT ACTION:\n{prompt}\n\n\
                     [This prompt was auto-generated by craft_next. Execute it now.]"
                )))
            }
            Err(e) => Ok(ToolResult::error(format!(
                "Failed to generate next prompt: {e}. Continue with your best judgment."
            ))),
        }
    }

    fn spec(&self) -> ToolSpec {
        ToolSpec {
            name: "craft_next".to_string(),
            description: "Generate your own next action prompt. Call this when you've completed \
                a task and want to strategically decide what to do next based on the user's \
                goals, project state, and what you've accomplished so far. The generated prompt \
                will guide your next actions. Also useful when the user gives a vague instruction \
                and you want to expand it into a specific, actionable plan."
                .to_string(),
            input_schema: serde_json::json!({
                "type": "object",
                "properties": {
                    "completed": {
                        "type": "string",
                        "description": "Brief summary of what you just finished"
                    },
                    "goal": {
                        "type": "string",
                        "description": "The user's overall objective you're working toward"
                    },
                    "context": {
                        "type": "string",
                        "description": "Relevant context: project state, recent findings, blockers, entity memory insights"
                    },
                    "constraints": {
                        "type": "string",
                        "description": "Any constraints or preferences to consider (optional)"
                    }
                },
                "required": ["completed", "goal"]
            }),
        }
    }

    fn name(&self) -> &str {
        "craft_next"
    }

    fn is_concurrent_safe(&self, _input: &serde_json::Value) -> bool {
        true // Side-query, no state mutation.
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // CraftNextTool requires a real provider, so we test the spec/name only.
    #[test]
    fn test_spec() {
        use sigil_core::traits::LogObserver;
        let spec =
            CraftNextTool::new(Arc::new(MockProvider), "test-model".into(), "shadow".into()).spec();
        assert_eq!(spec.name, "craft_next");
        assert!(spec.description.contains("next action"));
    }

    struct MockProvider;

    #[async_trait]
    impl Provider for MockProvider {
        async fn chat(
            &self,
            _request: &ChatRequest,
        ) -> anyhow::Result<sigil_core::traits::ChatResponse> {
            Ok(sigil_core::traits::ChatResponse {
                content: Some("Fix the auth bug in src/auth/validate.rs line 42.".into()),
                tool_calls: vec![],
                usage: sigil_core::traits::Usage {
                    prompt_tokens: 100,
                    completion_tokens: 20,
                },
                stop_reason: sigil_core::traits::StopReason::EndTurn,
            })
        }
        fn name(&self) -> &str {
            "mock"
        }
        async fn health_check(&self) -> anyhow::Result<()> {
            Ok(())
        }
    }

    #[tokio::test]
    async fn test_craft_next_generates_prompt() {
        let tool = CraftNextTool::new(Arc::new(MockProvider), "test-model".into(), "shadow".into());
        let result = tool
            .execute(serde_json::json!({
                "completed": "Fixed the null check",
                "goal": "Make auth module robust"
            }))
            .await
            .unwrap();

        assert!(!result.is_error);
        assert!(result.output.contains("NEXT ACTION"));
        assert!(result.output.contains("auth"));
    }
}
