use anyhow::Result;
use realm_core::traits::{ChatRequest, Message, MessageContent, Provider, Role};
use realm_quests::{Priority, Quest, QuestStatus};
use std::path::PathBuf;
use std::sync::Arc;
use tracing::{debug, info, warn};

const MAX_COMPLETED_QUESTS: usize = 5;
const MAX_INPUT_CHARS: usize = 8000;
const MAX_TOKENS: u32 = 1500;
const MAX_PROPOSALS: usize = 3;

/// A proposed quest generated by gap analysis.
#[derive(Debug, Clone)]
pub struct GapProposal {
    pub subject: String,
    pub description: String,
    pub priority: Priority,
    /// LLM confidence that this quest is genuinely needed now (0.0–1.0).
    pub confidence: f32,
    pub reasoning: String,
}

/// Autonomous gap analysis engine.
///
/// When a domain's quest queue empties, reads MEMORY.md and AGENTS.md from
/// the rig directory to identify the highest-impact remaining work.
///
/// - Confidence >= `auto_assign_threshold` (default 0.70): auto-create a quest
/// - Confidence < threshold: surface to Shadow via `WhisperKind::QuestProposal`
pub struct GapAnalyzer {
    pub domain_name: String,
    pub domain_prefix: String,
    /// Rig directory where MEMORY.md, AGENTS.md live.
    pub rig_dir: PathBuf,
    pub provider: Arc<dyn Provider>,
    pub model: String,
    /// Confidence threshold for autonomous quest creation (0.0–1.0).
    pub auto_assign_threshold: f32,
}

impl GapAnalyzer {
    pub fn new(
        domain_name: String,
        domain_prefix: String,
        rig_dir: PathBuf,
        provider: Arc<dyn Provider>,
        model: String,
    ) -> Self {
        Self {
            domain_name,
            domain_prefix,
            rig_dir,
            provider,
            model,
            auto_assign_threshold: 0.70,
        }
    }

    /// Analyze gaps and return ranked proposals (sorted by confidence descending).
    pub async fn analyze(
        &self,
        completed_quests: &[Quest],
        open_quests: &[Quest],
    ) -> Result<Vec<GapProposal>> {
        debug!(domain = %self.domain_name, "running gap analysis");

        let prompt = self.build_prompt(completed_quests, open_quests);

        let request = ChatRequest {
            model: self.model.clone(),
            messages: vec![Message {
                role: Role::User,
                content: MessageContent::text(&prompt),
            }],
            tools: vec![],
            max_tokens: MAX_TOKENS,
            temperature: 0.2,
        };

        let response = self.provider.chat(&request).await?;

        let Some(text) = response.content else {
            warn!(domain = %self.domain_name, "gap analysis: empty LLM response");
            return Ok(vec![]);
        };

        if text.trim() == "NO_GAPS" {
            info!(domain = %self.domain_name, "gap analysis: no gaps identified");
            return Ok(vec![]);
        }

        let mut proposals = parse_proposals(&text);
        proposals.sort_by(|a, b| b.confidence.partial_cmp(&a.confidence).unwrap_or(std::cmp::Ordering::Equal));

        info!(
            domain = %self.domain_name,
            count = proposals.len(),
            "gap analysis complete"
        );

        Ok(proposals)
    }

    fn build_prompt(&self, completed_quests: &[Quest], open_quests: &[Quest]) -> String {
        let mut prompt = format!(
            "You are the gap analysis system for the '{}' domain (prefix: {}).\n\
             Your task: identify the highest-impact work not yet done and propose concrete quests.\n\n",
            self.domain_name, self.domain_prefix
        );

        let mut chars_used = prompt.len();

        let agents_path = self.rig_dir.join("AGENTS.md");
        if let Ok(agents_content) = std::fs::read_to_string(&agents_path)
            && !agents_content.trim().is_empty() {
                let available = MAX_INPUT_CHARS.saturating_sub(chars_used);
                let chunk = &agents_content[..agents_content.len().min(available)];
                if !chunk.is_empty() {
                    prompt.push_str(&format!("## Domain Context (AGENTS.md)\n\n{chunk}\n\n"));
                    chars_used += chunk.len();
                }
            }

        let memory_path = self.rig_dir.join("MEMORY.md");
        if let Ok(memory_content) = std::fs::read_to_string(&memory_path)
            && !memory_content.trim().is_empty() {
                let available = MAX_INPUT_CHARS.saturating_sub(chars_used);
                let chunk = &memory_content[..memory_content.len().min(available)];
                if !chunk.is_empty() {
                    prompt.push_str(&format!("## Current Memory (MEMORY.md)\n\n{chunk}\n\n"));
                    chars_used += chunk.len();
                }
            }

        let recent: Vec<_> = completed_quests
            .iter()
            .filter(|q| q.status == QuestStatus::Done)
            .rev()
            .take(MAX_COMPLETED_QUESTS)
            .collect();

        if !recent.is_empty() {
            let available = MAX_INPUT_CHARS.saturating_sub(chars_used);
            if available > 100 {
                prompt.push_str("## Recently Completed Work\n\n");
                for q in &recent {
                    let summary = q.closed_reason.as_deref().unwrap_or(&q.subject);
                    let entry = format!("- {}: {}\n", q.id, summary);
                    if chars_used + entry.len() > MAX_INPUT_CHARS {
                        break;
                    }
                    prompt.push_str(&entry);
                    chars_used += entry.len();
                }
                prompt.push('\n');
            }
        }

        if !open_quests.is_empty() {
            let available = MAX_INPUT_CHARS.saturating_sub(chars_used);
            if available > 100 {
                prompt.push_str("## Currently Open Quests\n\n");
                for q in open_quests {
                    let entry = format!("- {}: {}\n", q.id, q.subject);
                    if chars_used + entry.len() > MAX_INPUT_CHARS {
                        break;
                    }
                    prompt.push_str(&entry);
                    chars_used += entry.len();
                }
                prompt.push('\n');
            }
        }

        prompt.push_str(&format!(
            "## Task\n\n\
             The quest queue is now empty. Based on the domain context, memory, and completed work above:\n\
             1. Identify gaps — work that is needed but not done\n\
             2. Evaluate impact — which gap has the highest value if closed\n\
             3. Propose up to {MAX_PROPOSALS} concrete quests (most impactful first)\n\n\
             For each proposal, output exactly:\n\
             PROPOSAL:\n\
             Subject: <one-line quest title>\n\
             Description: <2-4 sentences describing what the spirit should do>\n\
             Priority: high|normal|low\n\
             Confidence: <0.0–1.0 float — your confidence this is genuinely needed now>\n\
             Reasoning: <one sentence explaining why this is high-impact right now>\n\
             END PROPOSAL\n\n\
             Confidence guide:\n\
             - 0.9+: Critical gap, clearly needed based on domain backlog or memory\n\
             - 0.7–0.9: Strong signal this is needed based on context\n\
             - 0.5–0.7: Plausible but uncertain — surface to human for decision\n\
             - <0.5: Speculative — omit entirely\n\n\
             Rules:\n\
             - Only propose quests within this domain's scope\n\
             - Don't propose work already open or recently completed\n\
             - Prefer concrete actionable work over vague improvements\n\
             - If no gaps are clearly needed right now, output exactly: NO_GAPS\n\n\
             You have a 1500-token budget. Be concise."
        ));

        prompt
    }
}

/// Parse `PROPOSAL:` ... `END PROPOSAL` blocks from LLM output.
fn parse_proposals(text: &str) -> Vec<GapProposal> {
    let mut proposals = Vec::new();
    let mut pos = 0;

    while pos < text.len() {
        let remaining = &text[pos..];
        let Some(start) = remaining.find("PROPOSAL:") else {
            break;
        };

        let after_start = &remaining[start + 9..];
        let end_marker = "END PROPOSAL";

        let Some(end) = after_start.find(end_marker) else {
            break;
        };

        let block = &after_start[..end];
        if let Some(proposal) = parse_proposal_block(block) {
            proposals.push(proposal);
        }

        pos += start + 9 + end + end_marker.len();
    }

    proposals
}

fn parse_proposal_block(block: &str) -> Option<GapProposal> {
    let mut subject = String::new();
    let mut description_lines: Vec<String> = Vec::new();
    let mut priority = Priority::Normal;
    let mut confidence: f32 = 0.0;
    let mut reasoning = String::new();

    let mut in_description = false;

    for line in block.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        if let Some(val) = line.strip_prefix("Subject:") {
            subject = val.trim().to_string();
            in_description = false;
        } else if let Some(val) = line.strip_prefix("Description:") {
            let val = val.trim();
            if !val.is_empty() {
                description_lines.push(val.to_string());
            }
            in_description = true;
        } else if let Some(val) = line.strip_prefix("Priority:") {
            priority = match val.trim().to_lowercase().as_str() {
                "high" | "critical" => Priority::High,
                "low" => Priority::Low,
                _ => Priority::Normal,
            };
            in_description = false;
        } else if let Some(val) = line.strip_prefix("Confidence:") {
            confidence = val.trim().parse().unwrap_or(0.0);
            in_description = false;
        } else if let Some(val) = line.strip_prefix("Reasoning:") {
            reasoning = val.trim().to_string();
            in_description = false;
        } else if in_description {
            description_lines.push(line.to_string());
        }
    }

    if subject.is_empty() || confidence < 0.5 {
        return None;
    }

    Some(GapProposal {
        subject,
        description: description_lines.join(" "),
        priority,
        confidence,
        reasoning,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_single_proposal() {
        let text = "PROPOSAL:\nSubject: Fix authentication bug\nDescription: The login endpoint returns 500 for valid tokens.\nPriority: high\nConfidence: 0.85\nReasoning: Critical path bug blocking all users.\nEND PROPOSAL";
        let proposals = parse_proposals(text);
        assert_eq!(proposals.len(), 1);
        assert_eq!(proposals[0].subject, "Fix authentication bug");
        assert_eq!(proposals[0].priority, Priority::High);
        assert!((proposals[0].confidence - 0.85).abs() < 0.001);
    }

    #[test]
    fn test_parse_multiple_proposals() {
        let text = concat!(
            "PROPOSAL:\nSubject: Quest A\nDescription: Do A.\nPriority: high\nConfidence: 0.90\nReasoning: Critical.\nEND PROPOSAL\n",
            "PROPOSAL:\nSubject: Quest B\nDescription: Do B.\nPriority: normal\nConfidence: 0.75\nReasoning: Useful.\nEND PROPOSAL"
        );
        let proposals = parse_proposals(text);
        assert_eq!(proposals.len(), 2);
    }

    #[test]
    fn test_parse_low_confidence_filtered() {
        let text = "PROPOSAL:\nSubject: Speculative idea\nDescription: Maybe do this.\nPriority: low\nConfidence: 0.30\nReasoning: Not sure.\nEND PROPOSAL";
        let proposals = parse_proposals(text);
        assert!(proposals.is_empty(), "proposals with confidence < 0.5 should be filtered");
    }

    #[test]
    fn test_priority_parsing() {
        let block = "Subject: Test\nDescription: desc\nPriority: critical\nConfidence: 0.80\nReasoning: yes";
        let proposal = parse_proposal_block(block).unwrap();
        assert_eq!(proposal.priority, Priority::High);
    }

    #[test]
    fn test_priority_low() {
        let block = "Subject: Test low\nDescription: desc\nPriority: low\nConfidence: 0.75\nReasoning: minor";
        let proposal = parse_proposal_block(block).unwrap();
        assert_eq!(proposal.priority, Priority::Low);
    }

    #[test]
    fn test_no_gaps_returns_empty() {
        let text = "NO_GAPS";
        let proposals = parse_proposals(text);
        assert!(proposals.is_empty());
    }

    #[test]
    fn test_missing_subject_filtered() {
        let block = "Description: desc\nPriority: high\nConfidence: 0.90\nReasoning: yes";
        assert!(parse_proposal_block(block).is_none());
    }

    #[test]
    fn test_multiline_description() {
        let block = "Subject: Big task\nDescription: First line.\nSecond line.\nThird line.\nPriority: normal\nConfidence: 0.80\nReasoning: yes";
        let proposal = parse_proposal_block(block).unwrap();
        assert!(proposal.description.contains("First line"));
        assert!(proposal.description.contains("Second line"));
    }
}
